### ISSUE TITLE
Scanning Result not Working

### ISSUE THREAD

**Issue by BILLXZY1215** [HuangRunHua/ScanningDataCamera#1]
Hi, I'm using XCode 14.0 beta 4 and iOS 16.0 Beta 2, I installed the app successfully but when I'm trying to scan text, it does not shown on the CameraScanner, actually I think it did not call the `func dataScanner` but keeping showing me the warning message:

<img width="401" alt="截屏2022-08-07 13 29 28" src="https://user-images.githubusercontent.com/61944458/183276791-6a0ab8c6-bdd8-461e-8674-eeb662faef98.png">

Any workaround? Thanks in advance.

**Comment by HuangRunHua** [comment]
> Hi, I'm using XCode 14.0 beta 4 and iOS 16.0 Beta 2, I installed the app successfully but when I'm trying to scan text, it does not shown on the CameraScanner, actually I think it did not call the `func dataScanner` but keeping showing me the warning message:
> 
> <img alt="截屏2022-08-07 13 29 28" width="401" src="https://user-images.githubusercontent.com/61944458/183276791-6a0ab8c6-bdd8-461e-8674-eeb662faef98.png">
> 
> Any workaround? Thanks in advance.

Hi there, my dev environment is Xcode 14.0 beta 3, and I found the issue you described. The reason why this happens is because I set my camera to only scan `text` objects, it means only `String` can be recognized, if the picture you scan contains not only `String` or some words that can't be recognized as a string, it will show this alert.

And for this project, when you open the scan view, you need to tap the region which is surrounded by yellow markers, and then tap the cancel button to hide the scan view, you will find that the words you recognize is shown in the screen.

If the above method can't fix your problem, please let me know.

Please let me know the result. Enjoy coding.

**Comment by BILLXZY1215** [comment]
> > Hi, I'm using XCode 14.0 beta 4 and iOS 16.0 Beta 2, I installed the app successfully but when I'm trying to scan text, it does not shown on the CameraScanner, actually I think it did not call the `func dataScanner` but keeping showing me the warning message:
> > <img alt="截屏2022-08-07 13 29 28" width="401" src="https://user-images.githubusercontent.com/61944458/183276791-6a0ab8c6-bdd8-461e-8674-eeb662faef98.png">
> > Any workaround? Thanks in advance.
> 
> Hi there, my dev environment is Xcode 14.0 beta 3, and I found the issue you described. The reason why this happens is because I set my camera to only scan `text` objects, it means only `String` can be recognized, if the picture you scan contains not only `String` or some words that can't be recognized as a string, it will show this alert.
> 
> And for this project, when you open the scan view, you need to tap the region which is surrounded by yellow markers, and then tap the cancel button to hide the scan view, you will find that the words you recognize is shown in the screen.
> 
> If the above method can't fix your problem, please let me know.
> 
> Please let me know the result. Enjoy coding.

I see, thanks for the demonstration, now it's working properly.
